services:
  db:
    image: postgres:16
    container_name: freelance-manager-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=freelance_manager
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
