spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/freelance_manager
    username: app
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: false
